import torch
from TTS.api import TTS

# Ensure the correct device is set (e.g., "cpu" or "cuda")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Initialize the TTS model (e.g., English Tacotron2-DDC model)
model_name = "tts_models/en/ljspeech/tacotron2-DDC"
tts = TTS(model_name=model_name, progress_bar=False).to(device)

# Define the text and output file path
text = "Hello, this is a test message generated by the TTS model."
output_path = "english_output.wav"

# Generate and save the speech file
tts.tts_to_file(text=text, file_path=output_path)

print(f"Speech generated and saved to {output_path}")
